### ISSUE TITLE
Cannot find name 'HeadersInit'

### ISSUE THREAD

**Issue by gkhunger-sf** [leoek/fetch-to-curl#27]
Hi,

After updating to 0.5.0, it has started failing with:

```
node_modules/fetch-to-curl/types/main.d.ts:5:24 - error TS2304: Cannot find name 'HeadersInit'.

5     constructor(init?: HeadersInit);
```

Thanks,
Gaurav

**Comment by leoek** [comment]
Hi @gkhunger-sf from my understanding `HeadersInit` should usually be available in the types provided by typescript. How did you get that error (which typescript version, tsc cli or IDE)?

**Comment by leoek** [comment]
@gkhunger-sf I published 0.5.2 which includes the `HeadersInit` type. Can you please try whether the issue is gone with it?

**Comment by gkhunger-sf** [comment]
Updating to 0.5.2 fixed it. Thanks, Leonard!
